name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          script: |
            git config --global --add safe.directory ~/app
            cd ~/app
            git pull origin main

            cat > .env << 'EOF'
            MONGO_URI=${{ secrets.MONGO_URI }}
            DB_NAME=${{ secrets.DB_NAME }}
            MOCK_DB=false
            DEBUG=false
            JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}
            AWS_REGION=${{ secrets.AWS_REGION }}
            SES_SENDER_EMAIL=${{ secrets.SES_SENDER_EMAIL }}
            TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}
            EOF

            docker-compose down
            docker-compose up -d --build